### ISSUE TITLE
Research Searching options

### ISSUE THREAD

**Issue by jfredett** [LearnProgramming/Hatter#1]
Research Search LIbraries for Go
Research Full-text Search + Indexing Datastructures

**Comment by expez** [comment]
[mu](http://code.google.com/p/mu0/) looks pretty promising.

**Comment by jfredett** [comment]
Reiterating what I said in IRC. I think the two big features we need are:

1) No connection to a particular mailbox format (eg, Maildir, Mbox, etc)
2) A decent API we can bind to

There are probably other requirements, but that's what we need.
