### ISSUE TITLE
Research NCurses binding for Go

### ISSUE THREAD

**Issue by jfredett** [LearnProgramming/Hatter#2]
Research NCurses libraries for Go

Ideally ones with a high-level interface to designing UIs

**Comment by expez** [comment]
[This project](https://github.com/nsf/termbox-go) seems like it might be a good alternative to NCurses.  I believe the author is a Googler and wrote the termbox project (and later the go implementation termbox-go) specifically because the NCurses API is so shitty and hard to use.
