### ISSUE TITLE
Resurrect this project. We need some features 

### ISSUE THREAD

**Issue by Lbatson** [LearnProgramming/Hatter#21]
Bringing it back from the dead as something to have available for people to work on and with the end result of maybe having a workable client as intended. We need some more guidelines for features etc to add. We can bounce them around here and formalize them in issues/bugs as needed. @jfredett @SirSkidmore @expez @ZachMassia please weigh in on this and let's get it going again :+1:

**Comment by jfredett** [comment]
I have a host of features I'd like in a client, I'm happy to drive some feature development here, but I'm not sure how much I can do in terms of actual development work (due to my perpetual "holy shit how am I going to get all this done" level of busyness).

**Comment by Lbatson** [comment]
That's fine @jfredett. Just advising for direction of it would be good, occasional reviews would be cool too. I'm fairly newish to Ruby myself so the more complicated stuff would head your way possibly or anyone else that wants to step in. Also I'm working on getting it up and running but have no idea how to install/setup the termbox requirement so getting that much sorted to start it running again would also help

**Comment by ZachMassia** [comment]
I wouldn't mind working on this again.

I really haven't been doing any programming lately as I've been busy finishing up my last few courses. I also landed a diesel mechanic apprenticeship so this could be a fun little side project to get back into programming.

Are you on OSX @intothev01d ? I'm going to see if I can get it running tonight.

**Comment by Lbatson** [comment]
@ZachMassia yep I am, sounds good. Also, congrats on the job! If you can detail the steps or whatever in the README or wiki for reference I'll try to check it out tomorrow.

**Comment by ZachMassia** [comment]
I was able to install termbox no problem, however it seems that rb_termbox does not play well with Mac. 

For installing termbox, this is all it took:
`git clone git://github.com/nsf/termbox.git && cd termbox`
`./waf configure --prefix=/usr && ./waf`
`sudo ./waf install --destdir=/`

After pointing hatterrc to /usr/lib/libtermbox.dylib, running bin/hatter gives the following error:

```
/Users/zach/Dev/Github/Hatter/lib/hatter.rb:16:in `rescue in <top (required)>': undefined method   `shutdown' for nil:NilClass (NoMethodError)
from /Users/zach/Dev/Github/Hatter/lib/hatter.rb:6:in `<top (required)>'
from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/local/var/rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from ./hatter:3:in `<main>'
```

**Comment by Lbatson** [comment]
@ZachMassia Hmm, not sure what that error is. I've been playing around with cloud9 ide (service with an ubuntu instance and collaborative features, text editor, etc) and after following your info about installing termbox, running ./bin/hatter works fine. here's the version of ruby it's running
`ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]`
I'll have to test this out on my Mac when i get home. In case anyone wants to try out the environment I'm using here's a link to the editor https://ide.c9.io/intothev01d/hatter . The only problem i've noticed so far is that when it starts up any key presses whatsoever make it disappear. This could be a problem with cloud9 though.
Oh also, i had to change some of the require statements to require_relative to get things working but that may also be a symptom of the environment and not the project.

**Comment by jfredett** [comment]
`require_relative` is usually a misconfigured $LOAD_PATH smell. What things needed `relative`-ing?

**Comment by Lbatson** [comment]
@jfredett if you get a chance to take a look at the editor link above, the files i have open show the changes where i replaced require with require_relative.

**Comment by jfredett** [comment]
Ah, the issue looks like the gem is a bit misorganized, I'll see if I can
straighten things up. Most of the existing code should live beneath a
`lib/hatter/` directory. It looks like the gem was probably home-grown (via
mkdir's) rather than generated (by `bundle gem`).

**Comment by jfredett** [comment]
Looking at it more, there are some other issues (executable logic in `lib`,
as well as some other minor oddities (you shouldn't need to unshift any
loadpath stuff in `bin` in a well-organized gem).

**Comment by jfredett** [comment]
I'll have to poke at this tomorrow, I'm pretty knackered, but the punchline is that virtually everything in `lib` right now should be in `lib/hatter`, there should be a `lib/hatter.rb` which is the main entry point into the library stuff, and it should basically just be `requires` to pull in all needed dependencies and stuff. What's presently in `lib/hatter.rb` should really just be in `bin/hatter`, and then most of your `require_relative`s will just become `require`s,

**Comment by guycode** [comment]
Id like to start contributing to this project and a few other ruby open source projects if anyone has any suggestions on what would be helpful

**Comment by ChristianBagley** [comment]
I'd be interested in trying to, once again, resurrect this project. I think this would be an interesting project for those in the LearningProgramming community to work on; I know that I'd be especially curious to see where we can take it. Granted, even if we know that there may not be a groundbreaking client in the end, I think it'd be cool to see how far we can take it.

**Comment by jfredett** [comment]
I'm all for you all digging in and trying stuff, I'll advise where I can, but the direction of the project is up to you all. I'm just too busy to give this a ton of time.

My first recommendation would be to refactor this into the proper gem organizational structure (run `bundle gem` somewhere and then port the code here into that structure, putting stuff in `lib/hatter` with the entry point from `lib/hatter.rb`, etc.).
