### ISSUE TITLE
Research Unit/Integration Testing

### ISSUE THREAD

**Issue by jfredett** [LearnProgramming/Hatter#5]
Unit Testing -- How does it work in Go?

RSpec style?

What about integration tests

**Comment by expez** [comment]
The go toolchain includes a test framework.  This seems to be what most people are using.  More information about how to write tests can be found in the [documentation for the test package.](http://golang.org/pkg/testing/)

**Comment by expez** [comment]
I stumbled upon a [BDD testing framework called GoSpec.](https://github.com/orfjackal/gospec)  It looks pretty mature to me.

I also found [gocheck](http://labix.org/gocheck).  Gocheck takes the same approach as the test framework in the go tools, but it is a bit more elaborate. It affords, among other things, the creation of test fixtures (with the possibility to exclude costly setup from benchmark times) and test suites.

I get the sense that gocheck might be a bit overkill--from a technical standpoint--whereas the decision to use GoSpec is more about doing TDD or BDD.
