### ISSUE TITLE
lib for processing mail

### ISSUE THREAD

**Issue by expez** [LearnProgramming/Hatter#9]
I suggest we use www.github.com/mikel/mail aka the mail gem.  Using that lib will let us retrieve an email (from local dir or through POP) read and send email.

The only issue I see is that it reads .eml files.  I'm not sure how that affects our desire to support multiple mailbox formats.

**Comment by taylskid** [comment]
The Mail gem is really great; it's what I was looking at as well. I think it will compliment Hatter nicely.
